開発基礎講座
======

この講座はDL講座の補助となる講座です。

#### 対象

pythonは使った事はあるが、コーディングに自信がない人

#### 今回の講座で取得して欲しい事

DL講座を理解を助ける為のpythonに関する基礎知識

特にnumpyの使い方


# 予定
* pythonにおける開発方針(10分)
* ipython notebookを使おう(10分)
* numpyの配列処理(20分)
* 乱数を使った処理(5分)
* scikitlearn, scipy(15分)
* 質問、自習

# 内容
#### Pythonを使った開発
* なぜpythonか
* 注意すること

#### numpyの配列処理
* transpose, flatten, reshape
* dot product
* getting components, slice
* scalar multiplication
* ones, zeros
* axis
* numpy arrayのもつ関数(sum,max,min)
* broadcast, newaxis

#### 乱数
* 乱数生成 (ガウス分布、一様分布)
* 乱数を使った並び替え
* ランダムシード

#### scikitlearnの関数
* cross_validation

#### scipyの関数
* 画像処理

なぜ Pythonか
=======
* メジャーな言語

* ライブラリがそろっている。

* 便利な組み込み型 list, dictionary

* テキスト処理も簡単

* やりたい事が簡潔にかける

注意する事
=====
* 関数に入れた時のふるまい、コピー渡し、参照渡し

* pythonの '=' は エイリアス（別名）である。

* 実行ディレクトリにある ~.py　というファイルは全て import の対象となる。
<br>   numpy.py というファイルを現在作業中のディレクトリに置いてはいけない。

* import に関して
```
from numpy import *
```
としはいけません。
関数がどのモジュールで定義されたものか分かりづらくなる。


* numpyでは成分を一つずつ取り出して、行うような操作

    処理が遅くなる

#### コーディングスタンダード
    * PEP8
        https://www.python.org/dev/peps/pep-0008/
    * Google
        https://google.github.io/styleguide/pyguide.html

    PEP8に従っているかを自動でチェックする事も可能

#### 英語は開発者にも重要です

* ドキュメントを読む

* 正しい検索用語

* プログラミング

    普段から英語で書かれたマニュアルに目を通しておく事で語彙、表現を増やせる。


資料色々
====

正規

http://www.numpy.org/

http://docs.scipy.org/doc/

http://www.scipy.org/docs.html

Python Numpy Tutorial

http://cs231n.github.io/python-numpy-tutorial/

私訳「暫定的 NumPy チュートリアル」

http://naoyat.hatenablog.jp/entry/2011/12/29/021414

機械学習の Python との出会い

http://www.kamishima.net/mlmpyja/

Python Scientific Lecture Notes

http://turbare.net/transl/scipy-lecture-notes/index.html

ipython notebook を使おう
=============
## コードを書く、結果の確認が簡単にできる

* 実行

    再生ボタン
    
    (Ctrl + Enter)
    
    (Alt + Enter)新しいセルが作成される


* Auto Complete
    
    Tabキー


* Markdown と　Code
    
    Cell -> Cell Type -> (Code,.Markdown, RawNBConvert)


* 何コレ？と思ったらとりあえず '？' をつけてみよう
```
import numpy
numpy.linalg.det?
```
    %pdoc, dir　も使ってみよう
    

* linuxのコマンドは ! で
```
! ls
```

* 全部やり直し

    Kernel -> Restart


#### さらにいろいろやりたい人に
* magic関数

    %で始まる　ipython notebook 独自のコマンド
```
%magic
```
    でコマンドリストが見れる

#### 参照

http://ipython.org/notebook.html

http://opentechschool.github.io/python-data-intro/core/notebook.html

http://ameblo.jp/hitochan007/entry-11999446477.html

http://qiita.com/icoxfog417/items/175f69d06f4e590face9

### python 初学者がハマるいくつかの事

In [ ]:
a = [1,2,3]
b = a #エイリアス
b[1] = 3 #a[1] = 3 と同じ
a, b

In [ ]:
a = [1,2,3]
b=a[:] #コピー b=[1,2,3]と同じ
b[1] = 3
a, b

In [ ]:
a = [1,2,3]
b = [3,4,5]
a[0] = b[0] #代入
a[0] = 5 #代入
a, b

In [ ]:
# コピー渡し
def myfunction1(a, b ,c):
    a = b + c
    return a

x = 0
print myfunction1( x, 1, 2)
print myfunction1( x, 'ab', 'cd')
print x

In [ ]:
# 参照渡し
def myfunction2(dic):
    dic['A'] = 3 #dicが変更される
    return

d = {}
myfunction2(d)
print d

In [ ]:
#### Don't give name 'numpy.py'
! touch numpy.py
#! rm numpy.py numpy.pyc
#! ls

In [ ]:
import numpy as np

x = np.asarray([1,2,3])
print x

#### 本講座では重要ではありませんが、さらに知りたい人の為に。
予想と違う振る舞いの例　

http://www.toptal.com/python/top-10-mistakes-that-python-programmers-make

https://www.quora.com/What-are-common-programming-errors-or-gotchas-in-Python

http://inventwithpython.com/blog/2012/07/09/16-common-python-runtime-errors/

https://www.udacity.com/wiki/common-python-pitfalls

#### ベストプラクティスに従っていれば　問題ないはずです
#### わけのわからないエラーが出たら一行一行疑うことも必要

### 便利な機能

In [ ]:
import numpy
numpy.linalg.det?

In [ ]:
x?

# Numpyの使い方いろいろ

#### どうなるかを予想してから実行ボタンを押して下さい。

In [ ]:
import numpy as np
W = np.asarray([[1,2,3],[4,5,6]])
#W = np.asarray([[1,2,3,4],[4,5,6,7],[8,9,10,11]])

x = np.asarray([7,8,9])

print W
print
print x
print
# transpose
print W.T
print
#flatten 
print W.flatten()
print
#reshape
print W.reshape(3,2)

In [ ]:
# dot product
# 1*7 + 2*8 + 3*9 = 50
# 4*7 + 5*8 + 6*9 = 122
print np.dot(W,x)
print np.dot(x,W.T)

In [ ]:
# scalar multiplication
print W*2
print
print -W

In [ ]:
# components, slice
print x
print
print x[0]
print x[1]
print x[2]
print
print x[-1]
print
print x[::-1]
print
print x[::2]

In [ ]:
print W
print
print W[0]
print W[1]
print
print W[:,0]
print W[:,1]
print W[:,2]
print
print W[::-1]
print
print W[::-1,::-1]

In [ ]:
# axis, sum
print W
print
print W.sum()
print
print W.sum(axis=0)
print
print W.sum(axis=1)

In [ ]:
#　ones, zeros, reshape
print np.zeros(10)
print
print np.zeros(10).reshape(2,5)
print
print np.ones(10)
print
print (np.ones(10) * 0.5)
print
z = np.zeros(10)
z[:len(x)] += x
print z

#### broad castについての説明

http://sucrose.hatenablog.com/entry/2014/12/15/000352

In [ ]:
# broad cast
print W
print x
print
print x - 1
print
print W - 1
print
print W * x
print
print W + x

print 
# newaxis
print W.T + x[np.newaxis,:].T

In [ ]:
print W.shape
print W.T.shape
print
print x.shape
print x.T.shape # x と x.Tの shapeは同じ
print 
print x[np.newaxis,:].shape #(3,2)にbroadcastするには np.newaxisが必要
print
print x[:,np.newaxis]
print
print x[:,np.newaxis] * x
print 
print x[np.newaxis].shape #x[np.newaxis,:]と同じ
print x[:,np.newaxis].shape
#x[:,np.newaxis]はどんな表式かな？

In [ ]:
# squared norm
#sqrt(7*7 + 8*8 + 9*9) = 13.928....
x = np.asarray([7,8,9])
np.linalg.norm(x,ord=2)

#### 練習
* 1.
```
x = np.asarray([7,8,9])
W = np.asarray([[1,2,3],[4,5,6]])
```
と同様のx,Wを得るように np.arangeを使ったやり方を書いてください。


* 2.

    以下の様な表式を得るようにWを変形してください。
```
[[ 1.  0. -1.]
 [ 4.  3.  2.]]
```
    ヒント　縦の差は3,横の差は-1

In [ ]:
# write down your code

#W = np.asarray([[1,2,3],[4,5,6]])
#x = np.arange(7,XXX)
#W = np.arange(1,7).reshape(XXX,YYY)
#print x,W

#W[?????] - 2

#### 応用

以下の様な表式を得るようにnumpyでプログラムを書いてください。

* ex. 1
```
[0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
```

* ex. 2
```
[0, 1, 0, 3, 0, 5, 0, 7, 0, 9]
```

* ex. 3
```
[1, 2, 4, 8, 16]
```

* ex. 4
```
[-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
```

In [ ]:
# write down your code


### 乱数
ガウス型と一様乱数

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
#ipython notebookの時に必要
%matplotlib inline 

r = np.random.normal(0,10,1000) ### この数字を変えてみよう。
plt.plot(r,'x')
plt.show()
#np.random.normal?

In [ ]:
r = np.random.uniform(-10,10,1000) ### この数字を変えてみよう。
plt.plot(r,'x')
plt.show()
#np.random.uniform?

In [ ]:
import sklearn.utils
#random.seedを設定するといつも同じ乱数が生成される
np.random.seed(12345) ###ここをコメントアウトすると？, (123) => ()にすると？
print sklearn.utils.shuffle(range(10))
print sklearn.utils.shuffle(range(10))
print sklearn.utils.shuffle(range(10))

In [ ]:
### 応用編
rng = np.random.RandomState(12345)
print sklearn.utils.shuffle(range(10), random_state=rng)
print sklearn.utils.shuffle(range(10), random_state=rng)
print sklearn.utils.shuffle(range(10), random_state=rng)

In [ ]:
import string
lettersAtoE = string.uppercase[:5]
print lettersAtoE

from sklearn import cross_validation
cross_validation.train_test_split(range(5), lettersAtoE)
#ABCDEを01234と読みかえると?

In [ ]:
#MNIST 手書き数字データ

from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')
#mnist = fetch_mldata('MNIST original', data_home='.')

import matplotlib.pyplot as plt
%matplotlib inline 

#mnist.dataにはたくさんの画像データ（手書き数字）がはいっている。
plt.imshow(mnist.data[0].reshape(28,28),cmap='gray',interpolation='none')

In [ ]:
import scipy.ndimage

ZOOM=10  ### 変えてみよう
SIGMA=10   ### 変えてみよう
ANGLE=45  ### 変えてみよう

### 縮小拡大
img = scipy.ndimage.zoom(mnist.data[-1].reshape(28,28),(ZOOM,ZOOM),order=1)
### ぼかし
img = scipy.ndimage.gaussian_filter(img,SIGMA)
### 回転
img = scipy.ndimage.rotate(img,ANGLE)

plt.imshow(img, cmap='gray',interpolation='none')

In [ ]:
### 4枚をプロット　pyplot.figure
imgs = map(lambda x: x.reshape(28,28), sklearn.utils.shuffle(mnist.data))

fig = plt.figure()
ax = fig.add_subplot(1,4,1)
ax.imshow(imgs[0], cmap='gray',interpolation='none')
ax = fig.add_subplot(1,4,2)
ax.imshow(imgs[1], cmap='gray',interpolation='none')
ax = fig.add_subplot(1,4,3)
ax.imshow(imgs[2], cmap='gray',interpolation='none')
ax = fig.add_subplot(1,4,4)
ax.imshow(imgs[3], cmap='gray',interpolation='none')

#edge抽出など
#http://scikit-image.org/docs/dev/auto_examples/plot_canny.html
#http://www.tp.umu.se/~nylen/fnm/pylect/advanced/image_processing/index.html

#### 問題

mnist.dataには画像は何枚あるでしょうか。

画像データはどのようなグレイスケールで表されているでしょうか。

４枚の数字をタテ２xヨコ２で表示してみましょう

In [ ]:
#write down your code

In [ ]:
# 練習の解
print W[:,::-1] - 2

In [ ]:
#応用　ex.の解
print np.arange(10)/2
print (np.arange(10)*0.5).astype(int)
print

x = np.arange(10) 
x[x%2==0]=0
print x


x = np.arange(10)
print x * (x%2==1)
print

print 2**(np.arange(5))
print

print np.sign(np.arange(10)-4.5)
print np.concatenate([-np.ones(5), np.ones(5)])

In [ ]:
#問題の解
print len(mnist.data)
print mnist.data.max()
print mnist.data.min()
print (mnist.data % 1.0).any() #0.0以外があればこれは True
#(mnist.data % 1.0).sum()
#データ数　70000
#0~255までの整数

fig = plt.figure()
ax = fig.add_subplot(2,2,1)
ax.imshow(imgs[0], cmap='gray',interpolation='none')
ax = fig.add_subplot(2,2,2)
ax.imshow(imgs[1], cmap='gray',interpolation='none')
ax = fig.add_subplot(2,2,3)
ax.imshow(imgs[2], cmap='gray',interpolation='none')
ax = fig.add_subplot(2,2,4)
ax.imshow(imgs[3], cmap='gray',interpolation='none')