#第3回 演習課題（案）

##課題1．パーセプトロンを実装し，学習せよ．

In [1]:
import numpy as np
np.random.seed(1234)

In [2]:
class Linear:
    def __init__(self,in_dim,out_dim):
        self.W = np.random.normal(0,1,size=(in_dim,out_dim)).astype(np.float32)
        self.b = np.zeros(out_dim).astype(np.float32)

    def fprop(self,x):
        h  = np.dot(x,self.W)+self.b
        return h

class Step:
    def __init__(self):
        pass
    def fprop(self,x):
        h = np.sign(x)
        h[h==0]=1
        return h
    
def prop(layers, x):
    for i, layer in enumerate(layers):
        if i == 0:
            layer_out = layer.fprop(x)
        else:
            layer_out = layer.fprop(layer_out)
    return layer_out

X = np.array([[0,1],[1,0],[0,0],[1,1]])
y = np.array([[1],[1],[-1],[1]])

layers = [Linear(2,1),Step()]

mu = 1

for i in range(100):
    out = prop(layers,X)
    for i,o in enumerate(out):
        if o*y[i]!=1:
            layers[0].W = layers[0].W + mu*y[i]*X[i][np.newaxis,:].T
            layers[0].b = layers[0].b + mu*y[i]*np.ones(1)

print prop(layers,X)

[[ 1.]
 [ 1.]
 [-1.]
 [ 1.]]


##課題2．次の活性化関数とその微分を実装せよ．

In [3]:
class Sigmoid:
    def __init__(self):
        pass
    def fprop(self,x):
        return 1/(1+np.exp(-x))
    def bprop(self,x):
        return self.fprop(x)(1-self.fprop(x))
    
class Tanh:
    def __init__(self):
        pass
    def fprop(self,x):
        return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
    def bprop(self,x):
        return 1-self.fprop(x)**2

##課題3．これまでの実装を利用し，自由に順伝播ネットワークを構成し，出力を求めよ．

In [4]:
X = np.array([[0,1],[1,0],[0,0],[1,1]])

layers = [Linear(2,5),
          Sigmoid(),
          Linear(5,5),
          Tanh()]
out = prop(layers,X)
print out

[[-0.1211595   0.56719103  0.58218253 -0.49121413  0.21827793]
 [ 0.38342245 -0.27972626  0.69885318 -0.54063904  0.53556699]
 [ 0.32138817  0.34352702  0.59147232 -0.53339808  0.4166194 ]
 [ 0.08750672 -0.06047041  0.69542685 -0.51201038  0.41303291]]
